
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins_ci
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # Partage du socket Docker pour permettre à Jenkins de lancer des conteneurs (Molecule)
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    restart: unless-stopped
    networks:
      - jenkins-net

  jenkins-agent:
    image: jenkins/ssh-agent:latest-jdk17
    container_name: jenkins-agent
    restart: unless-stopped
    privileged: true # Nécessaire si vous voulez faire du Docker-in-Docker avancé
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3YR6Mj4Htl5SmsV1Ti/rwzhEG1SjKfb5jh3Vkk76+pE0IUqExJG0bxSne+nh4pelbMiG0m/XP9qgl0QIGzfiNmrrdil+DrtfC3wLc2UU1bmGDdDx9qv7S1vbhIgIAS/JhXW6iPbcD4Pbi9lTsISXFDFCj4KFfCCtXn/lIIJiPE4FLCistB3NeDmlGhZ2ZIoeR/QPL39kUVNR2DS0hW0LoGMmId8VC2m5mBj7nUSNe8Y0u4zNxFB9uFfusz8q+3GOBTDxRZph/K64nJSByriSA2Y6sBEPifJdnwQZKlMo1y3z/d9iLd/lRpMdCmW2DegI2XIO0MonKQrGssoHVHtAzJBbEfLlGMCh9qe7zwGXae42Tij6OZmxHOTzET9mbmjl7QccUEjjR30LwykGEuVptW3eFacQKL2GNV5lDYK8DY/3846OPwHc6tjUj8NfmuzVEtsiTvdyestPZxOcSXy0vJQbPMIO4wI4denEaEZNcHByZQXux5HGVWup5Fg4PfpFVGlSdLnRNVPyfHBJzEgBX+Ofdgpmbb/nGg0ktLsg31BbuXQV0ttWWeGNizP+cBxl0hSnOtUFGdMXGjrV0Sa0jtokBgKJ+9AO8IPwJaZjv5Vou1Amt8J2pkV1kIEjF1odk1YF8WhteDzZhEkk6sdfk9F1avoSECY7LUE9Ymj8MtQ== ytadjota@MP724
    volumes:
      # Permet à l'agent de lancer des conteneurs Docker sur l'hôte (Docker out of Docker)
      - /var/run/docker.sock:/var/run/docker.sock
      # Optionnel : si l'agent a besoin d'installer le binaire docker, ou utilisez une image custom
      - /usr/bin/docker:/usr/bin/docker:ro
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge