// 1. Importation obligatoire de la bibliothèque configurée globalement
// Le caractère "_" en fin de ligne est requis pour importer toutes les fonctions globales.
@Library('shared-libs@1.0.1') _

pipeline {
    agent any // S'exécute sur n'importe quel worker disponible disposant de Docker

    parameters {
        string(name: 'GIT_REPO', defaultValue: 'https://github.com/yvesconst/groovy-scripts.git', description: 'Url du repository Git')
        string(name: 'GIT_BRANCH_TO_TEST', defaultValue: 'main', description: 'Branche du dépôt de DAGs à valider')
        choice(name: 'TARGET_ENV', choices: ['staging', 'production'], description: 'Environnement cible pour simuler le déploiement')
        string(name: 'AIRFLOW_VERSION', defaultValue: '3.1.8', description: 'Version de destination d\'Airflow')
        text(name: 'DAG_PROJECTS_LIST', defaultValue: '', description: 'Liste des projets de dags à déployer')
    }

    environment {
        VENV_DIR       = '.venv_ci'
        REPO_URL       = "${params.GIT_REPO}"
        CREDENTIALS_ID = 'jenkins-git-ssh-private-key'
    }

    stages {
        stage('📥 Récupération des Sources') {
            steps {
                // Appel du module de checkout
                gitCheckout(
                    repoUrl: env.REPO_URL,
                    branch: params.GIT_BRANCH_TO_TEST,
                    credentialsId: env.CREDENTIALS_ID
                )
            }
        }

        stage('⚙️ Préparation des Paramètres') {
            steps {
                 script {
                    def playbookVars = [
                        target_environment: params.TARGET_ENV,
                        airflow_version: params.AIRFLOW_VERSION,
                        triggered_by_jenkins: true,
                        build_number: env.BUILD_NUMBER,
                        airflow_dags_installer: params.DAG_PROJECTS_LIST
                    ]

                    dir('ansible/roles/airflow.unittests') {
                        formatParamsToYaml(playbookVars, 'molecule/default/group_vars/all.yml')
                    }
                }
            }
        }

        stage('🐍 Configuration Environnement Python') {
            steps {
                installPythonEnv(
                    venvName: env.VENV_DIR
                )
            }
        }

        stage('🧪 Exécution du Test de Déploiement & Pytest') {
            steps {
                runAnsiblePipeline(
                    venvName: env.VENV_DIR
                )
            }
        }
    }

    post {
        always {
            echo 'Fin de la pipeline : Lancement du nettoyage de sécurité...'
            cleanWorker(
                venvName: env.VENV_DIR
            )
        }
    }
}