---
# Dependency management (download roles/collections)
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-certs: false
    ignore-errors: false
#    role-file: requirements.yml
#    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: airflow-test-env
    image: geerlingguy/docker-ubuntu2204-ansible:latest # Image avec Ansible préinstallé
    privileged: true
    pre_build_image: true
    groups:
      - runtime_env
  - name: airflow3-db
    image: postgres:15
    privileged: true
    groups:
      - database
    published_ports:
      - "5432:5432"
    env:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  # 2. Airflow Webserver
  - name: airflow3-webserver
    image: airflow-webserver:1.0.0-molecule
    privileged: true
    user: root                        # <-- Force Molecule to execute as root
    tty: true
    pre_build_image: true
    groups:
      - airflow
      - webserver
    published_ports:
      - "8085:8080"
    volumes:
      - "${MOLECULE_PROJECT_DIRECTORY}/files/dags:/opt/airflow/dags"
      - "${MOLECULE_PROJECT_DIRECTORY}/files/logs:/opt/airflow/logs"
      - "${MOLECULE_PROJECT_DIRECTORY}/files/config:/opt/airflow/config"
      - "${MOLECULE_PROJECT_DIRECTORY}/files/plugins:/opt/airflow/plugins"
      - "${MOLECULE_PROJECT_DIRECTORY}/files/config/airflow.cfg:/opt/airflow/airflow.cfg"
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    env:
      AIRFLOW_HOME: "/opt/airflow"
      AIRFLOW_DAG_FOLDER: "/opt/airflow/dags"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow3-db/airflow" # Ajusté avec le nom du conteneur Molecule
      AIRFLOW__CORE__FERNET_KEY: "fb39119b1d52d1335288279f06087799"
      AIRFLOW__API_FASTAPI__AUTH__TOKENS__JWT_SECRET: "e7f2b1c8a4d93e1b5c2f0a1d8e7b6c5a4d3e2f1b0c9d8e7f6a5b4c3d2e1f0a9b"
      AIRFLOW_CONFIG: "/opt/airflow/config/airflow.cfg"
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-fab-auth-manager"
      AIRFLOW__CORE__AUTH_MANAGER: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"
      _AIRFLOW_DB_UPGRADE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "admin"
      _AIRFLOW_WWW_USER_PASSWORD: "admin"
      _AIRFLOW_WWW_USER_ROLE: "Admin"
      _AIRFLOW_WWW_USER_EMAIL: "admin@example.com"
      AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8085"
      AIRFLOW__CORE__DAG_DISCOVERY_RECURSION_DEPTH: "5"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
      AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL: "10"
      AIRFLOW__CORE__MIN_SERIALIZED_DAG_FETCH_INTERVAL: "5"
    command: >
      bash -c "airflow db migrate
      && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.org --password admin
      && airflow api-server"

  # 3. Airflow Scheduler
  - name: airflow3-scheduler
    image: airflow-scheduler:1.0.0-molecule
    privileged: true
    user: root                        # <-- Force Molecule to execute as root
    tty: true
    pre_build_image: true
    groups:
      - airflow
      - scheduler
    volumes:
      - "${MOLECULE_PROJECT_DIRECTORY}/files/dags:/opt/airflow/dags"
      - "${MOLECULE_PROJECT_DIRECTORY}/files/logs:/opt/airflow/logs"
      - "${MOLECULE_PROJECT_DIRECTORY}/files/config:/opt/airflow/config"
      - "${MOLECULE_PROJECT_DIRECTORY}/files/plugins:/opt/airflow/plugins"
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    env:
      AIRFLOW_HOME: "/opt/airflow"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow3-db/airflow" # Ajusté avec le nom du conteneur Molecule
      AIRFLOW__API_FASTAPI__AUTH__TOKENS__JWT_SECRET: "e7f2b1c8a4d93e1b5c2f0a1d8e7b6c5a4d3e2f1b0c9d8e7f6a5b4c3d2e1f0a9b"
      AIRFLOW_CONFIG: "/opt/airflow/config/airflow.cfg"
      AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8085"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
      AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL: "10"
      AIRFLOW__CORE__MIN_SERIALIZED_DAG_FETCH_INTERVAL: "5"
    command: bash -c "sleep 30 && airflow db migrate && airflow scheduler"

provisioner:
  name: ansible

verifier:
  name: ansible

ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
      remote_tmp: /tmp/.ansible_${USER:-ansible}/tmp
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"
  playbooks:
    #    create: create.yml
    converge: converge.yml
    #    destroy: destroy.yml
    #    cleanup: cleanup.yml
    #    prepare: prepare.yml
    #    side_effect: side_effect.yml
    verify: verify.yml
#
#  executor:
#    backend: ansible-playbook
#    args:
#      ansible_playbook:
#        - --diff
#        - --force-handlers
#        - --inventory=../../inventory
#      ansible_navigator:
#        - --mode stdout
#        - --pull-policy missing
#        - --execution-environment-image ghcr.io/ansible/community-ansible-dev-tools:latest

scenario:
  name: default
  test_sequence:
    - dependency
#    - cleanup
#    - destroy
    - syntax
    - create
#    - prepare
    - converge
#    - idempotence
#    - side_effect
    - verify
#    - cleanup
#    - destroy
