[tox]
minversion = 4.0
# On définit explicitement l'environnement par défaut
envlist = py311-ansible12
skipsdist = true

[testenv]
# Indique à Tox d'utiliser 'uv' pour créer le venv et installer les dépendances


# CRUCIAL POUR UV : On associe explicitement les facteurs de l'envlist à la version de Python
# Cela force uv à utiliser (ou télécharger) Python 3.10
basepython = py311

passenv = *

deps =
    ansible-core>=2.13,<2.17
    molecule
    molecule-plugins[docker]
    pytest-molecule
    pytest
    pytest-ansible
    pytest-testinfra
    apache-airflow>=3.1.8
    apache-airflow-providers-http
   apache-airflow-providers-ssh

commands =
    molecule test --scenario-name default